#!/usr/bin/env python
# -*- coding: utf-8 -*-

from argent import Parser
from xerox import copy
from clint import piped_in


@Parser.from_function
def xi():
    """A little tool that copies output from stdin to the clipboard."""
    copy(piped_in())


xi.command_line()
